version: '3.3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kib01
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - "5602:5601"
    networks:
      - esnet
    volumes:
      - kibana:/usr/share/kibana
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      node.name: es01
      discovery.seed_hosts: es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es02
    environment:
      node.name: es02
      discovery.seed_hosts: es01,es03
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es03
    environment:
      node.name: es03
      discovery.seed_hosts: es01,es02
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
volumes:
  kibana:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  esnet:
