version: '3.3'
services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.0.0
    container_name: mb01
    environment:
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: beats_system
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: t0p.s3cr3t
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - esnet
    volumes:
      - metricbeat:/usr/share/metricbeat
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
# include this first time starting metricbeat
#    command:
#      - setup
#      - --dashboards
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.0.0
    container_name: fb01
    environment:
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: beats_system
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: t0p.s3cr3t
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://es01:9200
    user: root
    networks:
      - esnet
    volumes:
      - filebeat:/usr/share/filebeat
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
# include this first time starting filebeat
#    command:
#      - setup
#      - --dashboards
  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    container_name: ls01
    environment:
      XPACK_MONITORING_ENABLED: "true"
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: logstash_system
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: t0p.s3cr3t
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - esnet
    volumes:
      - logstash:/usr/share/logstash
      - ./pipeline:/usr/share/logstash/pipeline
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kib01
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_USERNAME: training
      ELASTICSEARCH_PASSWORD: my_password
    ports:
      - "5602:5601"
    networks:
      - esnet
    volumes:
      - kibana:/usr/share/kibana
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      node.name: es01
      discovery.seed_hosts: es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es02
    environment:
      node.name: es02
      discovery.seed_hosts: es01,es03
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es03
    environment:
      node.name: es03
      discovery.seed_hosts: es01,es02
      cluster.initial_master_nodes: es01,es02,es03
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
volumes:
  metricbeat:
    driver: local
  filebeat:
    driver: local
  logstash:
    driver: local
  kibana:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  esnet:
